Tick methods implementation in precompile
hubble-exchange/hubblenet pull request #100
Opened 2023-08-19 10:00 UTC by shubhamgoyal42

ValidatePlaceLimitOrder function is incomplete

2023-08-28 05:36 UTC, fdgod09 commented on precompile/contracts/juror/logic.go
> +		}
We dont need this check. It is already covered in contract and logic will return bidsHead if called anyway.
Same for asks

2023-08-28 05:41 UTC, fdgod09 commented on precompile/contracts/juror/logic.go
> +	if input.Tick.Sign() == 0 {
Dont need to check if input == 0. Logic can handle it. We allow 0 price orders

2023-08-31 02:31 UTC, atvanguard requested changes

2023-08-31 02:31 UTC, atvanguard commented on precompile/contracts/juror/logic.go
> +	baseQAtTick := new(big.Int).Div(new(big.Int).Mul(new(big.Int).Sub(impactMarginNotional, accNotional), big.NewInt(1e6)), tick)
should be multiplied by 1e18. Same for `SampleImpactAsk`

2023-08-31 02:31 UTC, atvanguard commented on precompile/contracts/bibliophile/client.go
> +	GetTakerFeeOB() *big.Int
Curious why create 2 separate instances to read from OB and CH.

2023-08-31 02:31 UTC, atvanguard commented on precompile/contracts/bibliophile/margin_account.go
> +func getMinAllowableMarginMA(stateDB contract.StateDB) *big.Int {
why do we need 3 flavours for getting the same thing? `OB, CH, MA`

2023-08-31 06:37 UTC, fdgod09 commented on precompile/contracts/juror/logic.go
> +	if order.Trader != trader && !bibliophile.IsTradingAuthority(order.Trader, trader) {
yes. tested it with unit tests

2023-08-31 06:56 UTC, fdgod09 commented on precompile/contracts/juror/logic.go
> +	if input.Tick.Sign() == 0 {
we dont allow 0 price orders

2023-08-31 12:28 UTC, atvanguard approved these changes

2023-08-31 12:28 UTC, merged