APIs for traders
hubble-exchange/hubblenet pull request #70
Opened 2023-06-19 10:48 UTC by shubhamgoyal42

2023-06-19 10:53 UTC, atvanguard requested changes

2023-06-19 10:53 UTC, atvanguard commented on plugin/evm/limitorders/memory_database.go
> +		Salt:                    "0x" + order.Salt.Text(16),
send this as normal string as well.

2023-06-19 11:01 UTC, shubhamgoyal42 commented on plugin/evm/limitorders/memory_database.go
> +		Salt:                    "0x" + order.Salt.Text(16),
updated

2023-06-20 09:34 UTC, atvanguard commented
Closing in favour of #71

2023-06-20 09:34 UTC, closed without merging